### ISSUE TITLE
Regex pattern for ignore_keys in JSON comparison is not always effective

### ISSUE THREAD

**Issue by ChingT** [VolumeGraphics/havocompare#52]
I've configured a file with the following settings:

```yaml
rules:
  - name: "Compare JSON files"
    pattern_include:
      - "**/*.json"
    Json:
      ignore_keys:
        - "^[a-zA-Z]+Id$"
```

Despite this configuration, the comparison results still show keys containing `xxxId`, which should have been ignored based on the specified regex pattern. However, some keys containing `Id` do get ignored.
